first working version

diff --git a/bin/jsii-release-golang b/bin/jsii-release-golang
--- a/bin/jsii-release-golang
+++ b/bin/jsii-release-golang
@@ -11,9 +11,8 @@ set -eu
 #
 # GITHUB_TOKEN       (required): Authentication token that allows to push and tag the repository.
 # GITHUB_REPO        (required): GitHub repository to push to.
+# VERSION            (required): Module version. Will be used as the repository tag. Required unless NO_TAG is set to a non-zero value.
 # GIT_BRANCH         (optional): Branch to push to. Defaults to 'main'.
-# NO_TAG             (optional): Disable repository tagging by specifying a non-zero value.
-# VERSION            (optional): Module version. Will be used as the repository tag. Required unless NO_TAG is set to a non-zero value.
 # GIT_USER_NAME      (optional): Username to perform the commit with. Defaults to the current username (git config user.name)
 # GIT_USER_EMAIL     (optional): Email to perform the commit with. Defaults to the current email (git config user.email)
 # GIT_COMMIT_MESSAGE (optional): The commit message. Defaults to the last commit of the current repository.
@@ -23,8 +22,10 @@ dir=${1:-dist/go}
 GIT_BRANCH=${GIT_BRANCH:-main}
 GIT_USER_NAME=${GIT_USER_NAME:-$(git config user.name)}
 GIT_USER_EMAIL=${GIT_USER_EMAIL:-$(git config user.email)}
-GIT_COMMIT_MESSAGE=${GIT_COMMIT_MESSAGE:-0}
-NO_TAG=${GIT_BRANCH:-$(git log -1 --format=%s)}
+GIT_COMMIT_MESSAGE=${GIT_COMMIT_MESSAGE:-$(git log -1 --format=%s)}
+
+# remember the full path since we might be changing dirs later on
+dir="$(pwd)/${dir}"
 
 if [ ! -f "${dir}/go.mod" ]; then
   echo "cannot find go.mod file in ${dir}/go.mod"
@@ -41,24 +42,29 @@ if [ -z "${GITHUB_REPO:-}" ]; then
   exit 1
 fi
 
-tempdir=$(mktemp -d)
-pushd ${tempdir}
+if [ -z "${VERSION:-}" ]; then
+  echo "VERSION env variable is required"
+  exit 1
+fi
+
+target_repo_dir=$(mktemp -d)/repo
 
 echo "Cloning target repository ${GITHUB_REPO}"
-git clone --branch ${GIT_BRANCH} https://${GITHUB_TOKEN}@${GITHUB_REPO} repo
+git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git ${target_repo_dir}
 
-echo "Copying go module to repository root"
-cp -r ${DIR} repo
-
+pushd ${target_repo_dir}
 git config user.name ${GIT_USER_NAME}
 git config user.email ${GIT_USER_EMAIL}
 
-git add .
-git commit --allow-empty -m ${GIT_COMMIT_MESSAGE}
-git push
+git checkout ${GIT_BRANCH}
 
-if [ ${NO_TAG} -eq 0 ]; then
-  git tag -a $VERSION -m "v$VERSION"
-  git push $VERSION
-fi
+echo "Copying go module to repository root"
+cp -r ${dir} .
+
+git add .
+git commit -m "\"${GIT_COMMIT_MESSAGE}\""
+git push origin ${GIT_BRANCH}
+git tag -a $VERSION -m $VERSION
+git push origin $VERSION
+
 popd
