feat(maven): GitHub packages support (#12)
Closes #11

- These restructures the maven release script to support non-nexus based repositories. In particular, a parallel execution path exists that simply uses the maven deploy plugin.
- At this particular time, signing is only supported for nexus repositories.
- The username, password, and gpg passphrase are also kept out of files and replaced with environment variable lookups.
- Did a bit of cleanup on error handling to route all single line errors through the `error` function

diff --git a/bin/jsii-release-maven b/bin/jsii-release-maven
--- a/bin/jsii-release-maven
+++ b/bin/jsii-release-maven
@@ -16,6 +16,8 @@ set -eu # we don't want "pipefail" to implement idempotency
 # MAVEN_GPG_PRIVATE_KEY_FILE       - GPG private key file (mutually exclusive with MAVEN_GPG_PRIVATE_KEY)
 # MAVEN_GPG_PRIVATE_KEY_PASSPHRASE - The passphrase of the provided key.
 # MAVEN_DRYRUN                     - Set to "true" for a dry run
+# MAVEN_SERVER_ID                  - Used in maven settings for credential lookup
+# MAVEN_REPOSITORY_URL             - Deployment repository when not deploying to maven central
 #
 ###
 
@@ -39,151 +41,186 @@ set -eu # we don't want "pipefail" to implement idempotency
 #
 ###
 
+readonly CENTRAL_SERVER="ossrh"
+scriptdir="$(cd $(dirname $0) && pwd)"
+
 error() { echo "❌ $@"; exit 1; }
 
-cd "${1:-"dist/java"}"
-
-[ -z "${MAVEN_STAGING_PROFILE_ID:-}" ] && error "MAVEN_STAGING_PROFILE_ID is required"
-[ -z "${MAVEN_USERNAME:-}" ] && error "MAVEN_USERNAME is required"
-[ -z "${MAVEN_PASSWORD:-}" ] && error "MAVEN_PASSWORD is required"
-
-[ -z "${MAVEN_GPG_PRIVATE_KEY_PASSPHRASE:-}" ] && error "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE is required"
-[ -z "${MAVEN_GPG_PRIVATE_KEY_FILE:-}" ] && [ -z "${MAVEN_GPG_PRIVATE_KEY:-}" ] && error "MAVEN_GPG_PRIVATE_KEY_FILE or MAVEN_GPG_PRIVATE_KEY is required"
-[ -n "${MAVEN_GPG_PRIVATE_KEY:-}" ] && [ -n "${MAVEN_GPG_PRIVATE_KEY_FILE:-}" ] && error "Cannot specify both MAVEN_GPG_PRIVATE_KEY and MAVEN_GPG_PRIVATE_KEY_FILE"
-
-if [[ -n "${MAVEN_DRYRUN:-}" ]]; then
-    echo "==========================================="
-    echo "            🏜️ DRY-RUN MODE 🏜️"
-    echo "==========================================="
-    mvn="echo mvn"
-    dry_run=true
-else
-    mvn=mvn
-    dry_run=false
-fi
-
-#---------------------------------------------------------------------------------------------------------------------------------------
-# Import private GPG key
-#---------------------------------------------------------------------------------------------------------------------------------------
-
-echo "Importing GPG key..." >&2
-
-# GnuPG will occasionally bail out with "gpg: <whatever> failed: Inappropriate ioctl for device", the following attempts to fix
-export GNUPGHOME=$(mktemp -d)
-export GPG_TTY=$(tty)
-
-
-if [ -n "${MAVEN_GPG_PRIVATE_KEY}" ]; then
-    MAVEN_GPG_PRIVATE_KEY_FILE="${GNUPGHOME}/private.pem"
-    echo -e "${MAVEN_GPG_PRIVATE_KEY}" > ${MAVEN_GPG_PRIVATE_KEY_FILE}
-fi
-
-gpg --allow-secret-key-import --batch --yes --no-tty --import "${MAVEN_GPG_PRIVATE_KEY_FILE}" || {
-    echo "❌ GPG key import failed"
-    exit 1
+validate_central_parameters() {
+    [[ -z "${MAVEN_STAGING_PROFILE_ID:-}" ]] && error "MAVEN_STAGING_PROFILE_ID is required"
+    return 0
 }
 
-gpg_key_id=$(gpg --list-keys --with-colons | grep pub | cut -d: -f5)
-echo "gpg_key_id=${gpg_key_id}"
+validate_non_central_parameters() {
+    [[ -z "${MAVEN_SERVER_ID:-}" ]] && error "MAVEN_SERVER_ID is required"
+    [[ -z "${MAVEN_REPOSITORY_URL:-}" ]] && error "MAVEN_REPOSITORY_URL is required"
+    return 0
+}
 
-GPG_PASSPHRASE_FROM_STDIN="--passphrase-fd 0"
-if [[ "$(uname)" == "Darwin" ]]; then
-    # On Mac, we must pass this to disable a prompt for
-    # passphrase, but option is not recognized on Linux.
-    GPG_PASSPHRASE_FROM_STDIN="${GPG_PASSPHRASE_FROM_STDIN} --pinentry-mode loopback"
-fi
-export GPG_PASSPHRASE_FROM_STDIN
+validate_signing_parameters() {
+    [[ -z "${MAVEN_GPG_PRIVATE_KEY_PASSPHRASE:-}" ]] && error "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE is required"
+    [[ -z "${MAVEN_GPG_PRIVATE_KEY_FILE:-}" ]] && [[ -z "${MAVEN_GPG_PRIVATE_KEY:-}" ]] && error "MAVEN_GPG_PRIVATE_KEY_FILE or MAVEN_GPG_PRIVATE_KEY is required"
+    [[ -n "${MAVEN_GPG_PRIVATE_KEY:-}" ]] && [[ -n "${MAVEN_GPG_PRIVATE_KEY_FILE:-}" ]] && error "Cannot specify both MAVEN_GPG_PRIVATE_KEY and MAVEN_GPG_PRIVATE_KEY_FILE"
+    return 0
+}
 
-poms="$(find . -name '*.pom')"
-if [ -z "${poms}" ]; then
-    echo "❌ No JARS to publish: no .pom files found under $PWD"
-    exit 1
-fi
+validate_parameters() {
+    [[ -z "${MAVEN_USERNAME:-}" ]] && error "MAVEN_USERNAME is required"
+    [[ -z "${MAVEN_PASSWORD:-}" ]] && error "MAVEN_PASSWORD is required"
 
-echo "📦 Publishing to Maven Central"
-staging=$(mktemp -d)
-workdir=$(mktemp -d)
+    if ${is_central}; then
+        validate_central_parameters
+    else
+        validate_non_central_parameters
+    fi
 
-# Create a settings.xml file with the user+password for maven
-mvn_settings="${workdir}/mvn-settings.xml"
-cat > ${mvn_settings} <<-EOF
+    if (${is_signed} && ! ${is_central}); then
+        error "Package signing is currently only supported for Maven Central"
+    fi
+
+    if (${is_signed} || ${is_central}); then
+        validate_signing_parameters
+    fi
+}
+
+import_gpg_key() {
+    #---------------------------------------------------------------------------------------------------------------------------------------
+    # Import private GPG key
+    #---------------------------------------------------------------------------------------------------------------------------------------
+
+    echo "Importing GPG key..." >&2
+
+    # GnuPG will occasionally bail out with "gpg: <whatever> failed: Inappropriate ioctl for device", the following attempts to fix
+    export GNUPGHOME=$(mktemp -d)
+    export GPG_TTY=$(tty)
+
+
+    if [ -n "${MAVEN_GPG_PRIVATE_KEY:-}" ]; then
+        MAVEN_GPG_PRIVATE_KEY_FILE="${GNUPGHOME}/private.pem"
+        echo -e "${MAVEN_GPG_PRIVATE_KEY}" > ${MAVEN_GPG_PRIVATE_KEY_FILE}
+    fi
+
+    gpg --allow-secret-key-import --batch --yes --no-tty --import "${MAVEN_GPG_PRIVATE_KEY_FILE}" || {
+        error "GPG key import failed"
+    }
+
+    gpg_key_id=$(gpg --list-keys --with-colons | grep pub | cut -d: -f5)
+    echo "gpg_key_id=${gpg_key_id}"
+
+    GPG_PASSPHRASE_FROM_STDIN="--passphrase-fd 0"
+    if [[ "$(uname)" == "Darwin" ]]; then
+        # On Mac, we must pass this to disable a prompt for
+        # passphrase, but option is not recognized on Linux.
+        GPG_PASSPHRASE_FROM_STDIN="${GPG_PASSPHRASE_FROM_STDIN} --pinentry-mode loopback"
+    fi
+    export GPG_PASSPHRASE_FROM_STDIN
+}
+
+create_maven_settings() {
+    # Create a settings.xml file with the user+password for maven
+    mvn_settings="${workdir}/mvn-settings.xml"
+    if ${is_signed}; then
+        cat > ${mvn_settings} <<-EOF
 <?xml version="1.0" encoding="UTF-8" ?>
 <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
-          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
-          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
-                              http://maven.apache.org/xsd/settings-1.0.0.xsd">
+        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
+                            http://maven.apache.org/xsd/settings-1.0.0.xsd">
   <servers>
     <server>
-      <id>ossrh</id>
-      <username>${MAVEN_USERNAME}</username>
-      <password>${MAVEN_PASSWORD}</password>
+      <id>${server_id}</id>
+      <username>\${env.MAVEN_USERNAME}</username>
+      <password>\${env.MAVEN_PASSWORD}</password>
+    </server>
+    <server>
+      <id>gpg.passphrase</id>
+      <passphrase>\${env.MAVEN_GPG_PRIVATE_KEY_PASSPHRASE}</passphrase>
     </server>
   </servers>
 </settings>
 EOF
+    else
+        cat > ${mvn_settings} <<-EOF
+<?xml version="1.0" encoding="UTF-8" ?>
+<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
+        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
+                            http://maven.apache.org/xsd/settings-1.0.0.xsd">
+  <servers>
+    <server>
+      <id>${server_id}</id>
+      <username>\${env.MAVEN_USERNAME}</username>
+      <password>\${env.MAVEN_PASSWORD}</password>
+    </server>
+  </servers>
+</settings>
+EOF
+    fi
+}
 
-echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-echo " Preparing repository"
-echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+sign_artifacts() {
+    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+    echo " Preparing repository"
+    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 
-# Sign and stage our artifacts into a local directory
-for pom in ${poms}; do
-    $mvn --settings=${mvn_settings} gpg:sign-and-deploy-file                    \
-        -Durl=file://${staging}                                                 \
-        -DrepositoryId=maven-central                                            \
-        -Dgpg.homedir=${GNUPGHOME}                                              \
-        -Dgpg.keyname=0x${gpg_key_id}                                           \
-        -Dgpg.passphrase=${MAVEN_GPG_PRIVATE_KEY_PASSPHRASE}                    \
-        -DpomFile=${pom}                                                        \
-        -Dfile=${pom/.pom/.jar}                                                 \
-        -Dsources=${pom/.pom/-sources.jar}                                      \
-        -Djavadoc=${pom/.pom/-javadoc.jar}
-done
+    # Sign and stage our artifacts into a local directory
+    for pom in ${poms}; do
+        $mvn --settings=${mvn_settings} gpg:sign-and-deploy-file                    \
+            -Durl=file://${staging}                                                 \
+            -DrepositoryId=${server_id}                                             \
+            -Dgpg.homedir=${GNUPGHOME}                                              \
+            -Dgpg.keyname=0x${gpg_key_id}                                           \
+            -Dgpg.executable="${scriptdir}/gpg-workaround.sh"                       \
+            -DpomFile=${pom}                                                        \
+            -Dfile=${pom/.pom/.jar}                                                 \
+            -Dsources=${pom/.pom/-sources.jar}                                      \
+            -Djavadoc=${pom/.pom/-javadoc.jar}
+    done
+}
 
+deploy_central() {
+    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+    echo " Deploying and closing repository..."
+    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 
-echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-echo " Deploying and closing repository..."
-echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+    staging_output="${workdir}/deploy-output.txt"
+    $mvn --settings=${mvn_settings}                                                    \
+        org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5:deploy-staged-repository \
+        -DrepositoryDirectory=${staging}                                               \
+        -DnexusUrl=${MAVEN_ENDPOINT:-https://oss.sonatype.org}                         \
+        -DserverId=${server_id}                                                        \
+        -DautoReleaseAfterClose=true                                                   \
+        -DstagingProfileId=${MAVEN_STAGING_PROFILE_ID} | tee ${staging_output}
 
-staging_output="${workdir}/deploy-output.txt"
-$mvn --settings=${mvn_settings}                                                    \
-    org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5:deploy-staged-repository \
-    -DrepositoryDirectory=${staging}                                               \
-    -DnexusUrl=${MAVEN_ENDPOINT:-https://oss.sonatype.org}                                            \
-    -DserverId=ossrh                                                               \
-    -DautoReleaseAfterClose=true                                                   \
-    -DstagingProfileId=${MAVEN_STAGING_PROFILE_ID} | tee ${staging_output}
+    # we need to consule PIPESTATUS sinec "tee" is the last command
+    if [ ${PIPESTATUS[0]} -ne 0 ]; then
+        error "Repository deployment failed"
+    fi
 
-# we need to consule PIPESTATUS sinec "tee" is the last command
-if [ ${PIPESTATUS[0]} -ne 0 ]; then
-    echo "❌ Repository deployment failed"
-    exit 1
-fi
+    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+    echo " Releasing repository"
+    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 
-echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-echo " Releasing repository"
-echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+    # Extract the ID of the closed repository from the log output of "deploy-staged-repository"
+    # This is because "deploy-staged-repository" doesn't seem to support autoReleaseAfterClose
+    # See https://issues.sonatype.org/browse/OSSRH-42487
+    if $dry_run; then
+        echo 'Closing staging repository with ID "dummyrepo"' > ${staging_output}
+    fi
 
-# Extract the ID of the closed repository from the log output of "deploy-staged-repository"
-# This is because "deploy-staged-repository" doesn't seem to support autoReleaseAfterClose
-# See https://issues.sonatype.org/browse/OSSRH-42487
-if $dry_run; then
-    echo 'Closing staging repository with ID "dummyrepo"' > ${staging_output}
-fi
+    repository_id="$(cat ${staging_output} | grep "Closing staging repository with ID" | cut -d'"' -f2)"
+    if [ -z "${repository_id}" ]; then
+        echo "❌ Unable to extract repository ID from deploy-staged-repository output."
+        echo "This means it failed to close or there was an unexpected problem."
+        echo "At any rate, we can't release it. Sorry"
+        exit 1
+    fi
 
-repository_id="$(cat ${staging_output} | grep "Closing staging repository with ID" | cut -d'"' -f2)"
-if [ -z "${repository_id}" ]; then
-    echo "❌ Unable to extract repository ID from deploy-staged-repository output."
-    echo "This means it failed to close or there was an unexpected problem."
-    echo "At any rate, we can't release it. Sorry"
-    exit 1
-fi
+    echo "Repository ID: ${repository_id}"
 
-echo "Repository ID: ${repository_id}"
-
-# Create a dummy pom.xml because the "release" goal needs one, but it doesn't care about it at all
-release_pom="${workdir}/release-pom.xml"
-cat > ${release_pom} <<HERE
+    # Create a dummy pom.xml because the "release" goal needs one, but it doesn't care about it at all
+    release_pom="${workdir}/release-pom.xml"
+    cat > ${release_pom} <<HERE
 <?xml version="1.0" encoding="UTF-8"?>
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
@@ -193,27 +230,110 @@ cat > ${release_pom} <<HERE
 </project>
 HERE
 
-# Release!
-release_output="${workdir}/release-output.txt"
-$mvn --settings ${mvn_settings} -f ${release_pom} \
-    org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5:release \
-    -DserverId=ossrh \
-    -DnexusUrl=${MAVEN_ENDPOINT:-https://oss.sonatype.org} \
-    -DstagingProfileId=${MAVEN_STAGING_PROFILE_ID} \
-    -DstagingRepositoryId=${repository_id} | tee ${release_output}
+    # Release!
+    release_output="${workdir}/release-output.txt"
+    $mvn --settings ${mvn_settings} -f ${release_pom}                 \
+        org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5:release \
+        -DserverId=${server_id}                                       \
+        -DnexusUrl=${MAVEN_ENDPOINT:-https://oss.sonatype.org}        \
+        -DstagingProfileId=${MAVEN_STAGING_PROFILE_ID}                \
+        -DstagingRepositoryId=${repository_id} | tee ${release_output}
 
-# If release failed, check if this was caused because we are trying to publish
-# the same version again, which is not an error. The magic string "does not
-# allow updating artifact" for a ".pom" file indicates that we are trying to
-# override an existing version. Otherwise, fail!
-if [ ${PIPESTATUS[0]} -ne 0 ]; then
-    if cat ${release_output} | grep "does not allow updating artifact" | grep -q ".pom"; then
-        echo "⚠️ Artifact already published. Skipping"
-    else
-        echo "❌ Release failed"
-        exit 1
+    # If release failed, check if this was caused because we are trying to publish
+    # the same version again, which is not an error. The magic string "does not
+    # allow updating artifact" for a ".pom" file indicates that we are trying to
+    # override an existing version. Otherwise, fail!
+    if [ ${PIPESTATUS[0]} -ne 0 ]; then
+        if cat ${release_output} | grep "does not allow updating artifact" | grep -q ".pom"; then
+            echo "⚠️ Artifact already published. Skipping"
+        else
+            error "Release failed"
+        fi
     fi
-fi
+}
 
-echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-echo "✅ All Done!"
+deploy_non_central() {
+    release_output="${workdir}/release-output.txt"
+    for pom in ${poms}; do
+        $mvn --settings=${mvn_settings} deploy -f ${pom} -DaltDeploymentRepository=${server_id}::default::${MAVEN_REPOSITORY_URL} | tee ${release_output}
+
+        # If release failed, check if this was caused because we are trying to publish
+        # the same version again, which is not an error. The magic string "409 Conflict"
+        # indicates that we are trying to
+        # override an existing version. Otherwise, fail!
+        if [ ${PIPESTATUS[0]} -ne 0 ]; then
+            if cat ${release_output} | grep -q "409 Conflict"; then
+                echo "⚠️ Artifact already published. Skipping"
+            else
+                error "Release failed"
+            fi
+        fi
+    done
+}
+
+main() {
+    cd "${1:-"dist/java"}"
+
+    server_id="${MAVEN_SERVER_ID:-"${CENTRAL_SERVER}"}"
+    if [[ "${server_id}" == "${CENTRAL_SERVER}" ]]; then
+        is_central=true
+    else
+        is_central=false
+    fi
+
+    if [[ -n "${MAVEN_GPG_PRIVATE_KEY_FILE:-}" ]] || [[ -n "${MAVEN_GPG_PRIVATE_KEY:-}" ]]; then
+        is_signed=true
+    else
+        is_signed=false
+    fi
+
+    validate_parameters
+
+    if [[ -n "${MAVEN_DRYRUN:-}" ]]; then
+        echo "==========================================="
+        echo "            🏜️ DRY-RUN MODE 🏜️"
+        echo "==========================================="
+        mvn="echo mvn"
+        dry_run=true
+    else
+        mvn=mvn
+        dry_run=false
+    fi
+
+    if ${is_signed}; then
+        import_gpg_key
+    fi
+
+    poms="$(find . -name '*.pom')"
+    if [ -z "${poms}" ]; then
+        error "No JARS to publish: no .pom files found under $PWD"
+    fi
+
+    if ${is_central}; then
+        echo "📦 Publishing to Maven Central"
+    else
+        echo "📦 Publishing to ${server_id}"
+    fi
+    
+    staging=$(mktemp -d)
+    workdir=$(mktemp -d)
+    echo ${workdir}
+
+    create_maven_settings
+
+    if ${is_signed}; then
+        # This currently only works with Maven Central
+        sign_artifacts
+    fi
+
+    if ${is_central}; then
+        deploy_central
+    else
+        deploy_non_central
+    fi
+
+    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+    echo "✅ All Done!"
+}
+
+main "$@"; exit
